version: "3.8" # Specify the docker-compose version

services:
  nodejs: # Replace with your application name
    build: . # Build the image from the current directory (context)
    ports:
      - "4000:4000" # Map container port 3000 to host port 3000
    image: server_image
    volumes:
      - ./server:/app/server # Mount the current directory as /app inside the container
      - /app/server/node_modules

  arangodb:
    image: arangodb:3.11.3
    container_name: arangodb_container
    restart: always
    ports:
      - 8529:8529
    environment:
      - ARANGO_NO_AUTH=1
    volumes:
      - ./server/arangodb:/var/lib/arangodb3
    networks:
      - uw_docker_network

  nextjs:
    container_name: nextjs_docker_container
    ports:
      - 3000:3000
    image: client_image
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    networks:
      - uw_docker_network

networks:
  uw_docker_network:
