version: "3.8" # Specify the docker-compose version

services:
  nodejs: # Replace with your application name
    build: . # Build the image from the current directory (context)
    image: server_image
    volumes:
      - ./server:/app/server # Mount the current directory as /app inside the container
      - /app/server/node_modules
    networks:
      - uw_docker_network
    depends_on:
      - arangodb

  arangodb:
    image: arangodb:3.11.3
    container_name: arangodb_container
    restart: always
    environment:
      - ARANGO_NO_AUTH=1
    volumes:
      - ./server/arangodb:/var/lib/arangodb3
    networks:
      - uw_docker_network

  nextjs:
    container_name: nextjs_docker_container
    image: client_image
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    networks:
      - uw_docker_network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    ports:
      - 80:80
    depends_on:
      - nextjs
    networks:
      - uw_docker_network


networks:
  uw_docker_network:
